server:
  port: 8085

spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/payment_service_of_booking_system?createDatabaseIfNotExist=true
    username: root
    password: 18032003
    driver-class-name: com.mysql.cj.jdbc.Driver